#[allow(clippy::too_many_arguments)]
pub fn generate_apkbuild(
    app_name: &str,
    version: &str,
    description: &str,
    homepage: &str,
    license: &str,
    repo: &str,
    x64_hash: Option<&str>,
    arm64_hash: Option<&str>,
) -> String {
    let clean_repo = repo
        .trim_start_matches("https://github.com/")
        .trim_start_matches("http://github.com/")
        .trim_end_matches(".git");
    let clean_v = version.trim_start_matches('v');

    let x64_h = x64_hash.unwrap_or("SKIP");
    let arm64_h = arm64_hash.unwrap_or("SKIP");

    let clean_desc = description
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('$', "\\$")
        .replace('`', "\\`");
    let clean_home = homepage
        .replace('\\', "\\\\")
        .replace('"', "\\\"");
    let clean_lic = license
        .replace('\\', "\\\\")
        .replace('"', "\\\"");

    format!(
        r#"# Maintainer: Generated by system-releaser
pkgname="{app_name}"
pkgver="{clean_v}"
pkgrel=0
pkgdesc="{clean_desc}"
url="{clean_home}"
arch="x86_64 aarch64"
license="{clean_lic}"
options="!check"

source_x86_64="https://github.com/{clean_repo}/releases/download/v$pkgver/${{pkgname}}_${{pkgver}}_linux_amd64.tar.gz"
source_aarch64="https://github.com/{clean_repo}/releases/download/v$pkgver/${{pkgname}}_${{pkgver}}_linux_arm64.tar.gz"

sha256sums_x86_64="{x64_h}"
sha256sums_aarch64="{arm64_h}"

package() {{
    install -Dm755 "$srcdir/$pkgname" "$pkgdir/usr/bin/$pkgname"
}}
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_apkbuild_generation() {
        let apkbuild = generate_apkbuild(
            "my-cli",
            "0.5.0",
            "Alpine CLI",
            "https://alpine.cli",
            "MIT",
            "https://github.com/alpine/my-cli",
            Some("sha_apk_64"),
            Some("sha_apk_arm"),
        );

        assert!(apkbuild.contains("pkgname=\"my-cli\""));
        assert!(apkbuild.contains("pkgver=\"0.5.0\""));
        assert!(apkbuild.contains("sha256sums_x86_64=\"sha_apk_64\""));
        assert!(apkbuild.contains("install -Dm755 \"$srcdir/$pkgname\" \"$pkgdir/usr/bin/$pkgname\""));
    }
}
