#[allow(clippy::too_many_arguments)]
pub fn generate_pkgbuild(
    app_name: &str,
    version: &str,
    description: &str,
    homepage: &str,
    license: &str,
    repo: &str,
    x64_hash: Option<&str>,
    arm64_hash: Option<&str>,
) -> String {
    let clean_repo = repo
        .trim_start_matches("https://github.com/")
        .trim_start_matches("http://github.com/")
        .trim_end_matches(".git");
    let clean_v = version.trim_start_matches('v');

    let x64_h = x64_hash.unwrap_or("SKIP");
    let arm64_h = arm64_hash.unwrap_or("SKIP");

    let clean_desc = description
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('$', "\\$")
        .replace('`', "\\`");
    let clean_home = homepage
        .replace('\\', "\\\\")
        .replace('"', "\\\"");
    let clean_lic = license
        .replace('\\', "\\\\")
        .replace('\'', "'\\''");

    format!(r#"# Maintainer: Generated by system-releaser
pkgname={app_name}-bin
pkgver={clean_v}
pkgrel=1
pkgdesc="{clean_desc}"
arch=('x86_64' 'aarch64')
url="{clean_home}"
license=('{clean_lic}')
provides=('{app_name}')
conflicts=('{app_name}')

source_x86_64=("https://github.com/{clean_repo}/releases/download/v${{pkgver}}/{app_name}_${{pkgver}}_linux_amd64.tar.gz")
sha256sums_x86_64=('{x64_h}')

source_aarch64=("https://github.com/{clean_repo}/releases/download/v${{pkgver}}/{app_name}_${{pkgver}}_linux_arm64.tar.gz")
sha256sums_aarch64=('{arm64_h}')

package() {{
  install -Dm755 "${{srcdir}}/{app_name}" "${{pkgdir}}/usr/bin/{app_name}"
}}
"#)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_pkgbuild_generation() {
        let pkgbuild = generate_pkgbuild(
            "my-tool",
            "1.0.0",
            "Pacman CLI",
            "https://mytool.dev",
            "MIT",
            "https://github.com/myorg/my-tool",
            Some("sha_x64"),
            Some("sha_arm64"),
        );

        assert!(pkgbuild.contains("pkgname=my-tool-bin"));
        assert!(pkgbuild.contains("sha256sums_x86_64=('sha_x64')"));
        assert!(pkgbuild.contains("install -Dm755"));
    }
}
