name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Build & Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run system-releaser
        uses:  Kishan-Agarwal-28/system-releaser-action@v0.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
